version: "3"

services:
  db:
    container_name: k8s-postgres
    image: postgres:14.0-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
      container_name: k8s-backend
      build: ./backend_main_django
      restart: unless-stopped
      ports:
        - 8000:80
      volumes:
        - ./backend_main_django:/code
      env_file:
        - ./.env
      depends_on:
        - db

volumes:
  postgres_volume:
